variables:
  NODE_JS_VERSION: 10.15.0

trigger:
  branches:
    include:
      - master
      - azure/*
  tags:
    include:
      - v*

jobs:
  - job: test_augur_node
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_JS_VERSION)
      - bash: |
          yarn
          npm run build:ts
          npm run lint
          npm run test
        displayName: 'lint, test, and build'

  - job: deploy_augur_node
    dependsOn:
      - test_augur_node
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_JS_VERSION)
      - task: Docker@1
        displayName: docker login
        inputs:
          command: login
          containerRegistryType: Container Registry
          dockerRegistryEndpoint: dockerhub-augurproject
      - bash: |
          set -euxo pipefail
          npm run docker:release -- dev
        displayName: docker release dev
        env:
          AWS_ACCESS_KEY_ID: $(AWS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)
        condition: |
          and
          (
              succeeded(),
              eq(variables['Build.SourceBranch'], 'refs/heads/master')
          )
      - bash: |
          set -euxo pipefail
          npm run docker:release -- tag
        displayName: docker release tag
        env:
          AWS_ACCESS_KEY_ID: $(AWS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)
        condition: |
          and
          (
              succeeded(),
              startsWith(variables['build.sourceBranch'], 'refs/tags/v')
          )
      - task: Docker@1
        displayName: docker logout
        inputs:
          command: logout
          containerRegistryType: Container Registry
          dockerRegistryEndpoint: dockerhub-augurproject
