variables:
  NODE_JS_VERSION: 10.15.0

trigger:
  branches:
    include:
      - master
      - azure/*
  tags:
    include:
      - v*

jobs:
  - job: test_augur_node
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_JS_VERSION)
      - bash: |
          set -euo pipefail
          yarn
          npm run build:ts
          npm run lint
          npm run test
        displayName: 'lint, test, and build'

  - job: deploy_augur_node
    dependsOn:
      - test_augur_node
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_JS_VERSION)
      - task: Docker@1
        displayName: docker login
        inputs:
          command: login
          containerRegistryType: Container Registry
          dockerRegistryEndpoint: dockerhub-augurproject
      - bash: |
          set -euxo pipefail
          yarn
          npm run docker:release -- dev
        displayName: docker release dev
        env:
          AWS_ACCESS_KEY_ID: $(AWS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)
      - task: Docker@1
        displayName: docker logout
        inputs:
          command: logout
          containerRegistryType: Container Registry
          dockerRegistryEndpoint: dockerhub-augurproject
    condition: |
      and
      (
          succeeded(),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
      )


  - job: tag_build
    displayName: build tag
    dependsOn:
      - test_augur_node
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_JS_VERSION)
      - task: Docker@1
        displayName: docker login
        inputs:
          command: login
          containerRegistryType: Container Registry
          dockerRegistryEndpoint: dockerhub-augurproject
      - bash: |
          set -euo pipefail
          current_tag=$(git describe --exact-match --tags)
          if [[ -n $current_tag ]]; then
            echo "${current_tag}"
            LATEST_VERSION_REGEX="^[vV]?(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
            DEV_VERSION_REGEX="^[vV]?(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"
            if [[ $current_tag =~ $LATEST_VERSION_REGEX ]]; then
              echo "##vso[task.setvariable variable=npm_tag]latest"
              yarn
              npm run docker:release -- latest
            elif [[ $current_tag =~ $DEV_VERSION_REGEX ]]; then
              echo "##vso[task.setvariable variable=npm_tag]dev"
            else
              # we should never get here
              echo "tag ${current_tag} doesn't match semver"
              echo "##vso[task.setvariable variable=npm_tag]random"
            fi
          fi
        env:
          AWS_ACCESS_KEY_ID: $(AWS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)
        displayName: set npm tag and release
      - task: Docker@1
        displayName: docker logout
        inputs:
          command: logout
          containerRegistryType: Container Registry
          dockerRegistryEndpoint: dockerhub-augurproject
      - bash: |
          set -euo pipefail
          yarn
          yarn build
      - task: Npm@1
        inputs:
          command: 'custom' # Options: install, publish, custom
          verbose: true
          customCommand: publish --tag $(npm_tag)
          customRegistry: 'useNpmrc'
          customEndpoint: npmjs-augur-integration
    condition: |
      and
      (
          succeeded(),
          startsWith(variables['build.sourceBranch'], 'refs/tags/v')
      )

